CC = cc
CFLAGS =  -c 
PROGRAM = CmapT 
OBJS = CmapT.o Cmap.o


LIBS = -lm -lXt -lX11 -lm

all:	$(PROGRAM) 

$(PROGRAM) :  $(OBJS)
	      $(CC) -o $@ $(OBJS) $(LIBS)

$(OBJS): Cmap.h CmapP.h

clean  : 
	 rm -f $(OBJS) $(PROGRAM)
